packages:
  - 'module-*'
  - 'slide-deck'
  - 'module-*/slides'
  - 'module-*/demo/*'
  - 'module-*/exercises/*/starter'
  - 'module-*/exercises/*/solution'
  - 'extras/*/exercises/*/starter'
  - 'extras/*/exercises/*/solution'
